### ISSUE TITLE
Errors when running gulp tasks

### ISSUE THREAD

**Issue by paulsjv** [tniswong/web-build#1]
I just pulled this down and installed everything but then got these errors when running a couple of tasks.

``` bash
jay.paulson at localadmins-MacBook-Pro-2 in ~/git/web-build on master
$ gulp prview:dist
[16:14:04] Requiring external module babel-core/register
[16:14:29] Using gulpfile ~/git/web-build/gulpfile.babel.js
[16:14:29] Task 'prview:dist' is not in your gulpfile
[16:14:29] Please check the documentation for proper gulpfile formatting

jay.paulson at localadmins-MacBook-Pro-2 in ~/git/web-build on master
$ gulp
[16:14:59] Requiring external module babel-core/register
[16:15:11] Using gulpfile ~/git/web-build/gulpfile.babel.js
[16:15:11] Starting 'jshint'...
[16:15:11] Starting 'clean:reports'...
[16:15:11] Starting 'clean:work'...
[16:15:11] Finished 'clean:reports' after 25 ms
[16:15:11] Starting 'reports:complexity'...
[16:15:11] Finished 'reports:complexity' after 13 ms
[16:15:11] Finished 'clean:work' after 33 ms
[16:15:11] Starting 'assets'...
[16:15:11] Starting 'bundle:dev:js'...
[16:15:11] Starting 'bundle:dev:sass'...
Error in plugin 'sass'
Message:
    www/sass/web-build.css
  7:9  file to import not found or unreadable: ../../jspm_packages/github/angular/bower-angular@1.4.6/angular-csp
Current dir: 
[16:15:17] Finished 'bundle:dev:sass' after 5.85 s
Unhandled rejection Error: ENOENT, open '/Users/jay.paulson/git/web-build/jspm_packages/npm/babel-core@5.8.25.js'
    at process._tickCallback (node.js:419:13)
From previous event:
    at DestroyableTransform._transform (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/index.js:40:10)
    at DestroyableTransform.Transform._read (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at DestroyableTransform.ondata (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:574:20)
    at DestroyableTransform.emit (events.js:95:17)
    at readableAddChunk (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:198:16)
    at DestroyableTransform.Readable.push (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DestroyableTransform.Transform.push (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at DestroyableTransform.sourceMapInit [as _transform] (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/index.js:122:10)
    at DestroyableTransform.Transform._read (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
[16:15:17] Finished 'jshint' after 6.31 s
[16:15:17] Starting 'test:unit'...
[16:15:22] Finished 'assets' after 11 s
[16:15:22] Starting 'assets:dev'...
[16:15:22] Finished 'assets:dev' after 34 μs
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not an object (evaluating 'System.config')
  at /Users/jay.paulson/git/web-build/node_modules/karma-jspm/src/adapter.js:18


PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: System
  at /Users/jay.paulson/git/web-build/config.js:1


Unhandled rejection Error: Not running
    at Server.close (net.js:1236:11)
    at /Users/jay.paulson/git/web-build/node_modules/karma/lib/server.js:338:17
    at tryCatcher (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
[16:15:26] 'test:unit' errored after 8.41 s
[16:15:26] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:95:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/jay.paulson/git/web-build/node_modules/karma/lib/server.js:329:7)
    at Server.<anonymous> (/Users/jay.paulson/git/web-build/node_modules/karma/lib/server.js:340:9)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:117:20)
    at net.js:1276:10
    at process._tickCallback (node.js:419:13)
[16:15:29] 'test:unit' errored after 11 s
[16:15:29] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:95:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at [object Object].removeAllListeners [as _onTimeout] (/Users/jay.paulson/git/web-build/node_modules/karma/lib/server.js:329:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by tniswong** [comment]
Not an issue. Run `npm install && jspm install`. Will add this to the README

**Comment by paulsjv** [comment]
I had to install jspm to get it to work :) However, below are the issues I ran into after installing everything.  My guess is that it might be on my end but wanted to report back so that you would be aware in case it had something to do with the framework.

```
npm install jspm -g
```

After doing this and running:

```
jspm install
```

I got the following error.

```
warn Error on download for github:jspm/nodelibs-fs
     Error: getaddrinfo ENOTFOUND
         at errnoException (dns.js:37:11)
         at Object.onanswer [as oncomplete] (dns.js:124:16)

err  Error: Error downloading github:jspm/nodelibs-fs.
         at cfg (/Users/jay.paulson/git/web-build/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:23:9)
         at Object.lib$rsvp$events$$default.trigger (/Users/jay.paulson/git/web-build/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:245:13)
         at null._onTimeout (/Users/jay.paulson/git/web-build/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:779:47)
         at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
ok   Installed github:systemjs/plugin-json@^0.1.0 (0.1.0)

err  Error downloading github:jspm/nodelibs-fs.
```

I still tried to run "gulp" and got a "too many files open" error:

```
$ gulp
[08:48:08] Requiring external module babel-core/register
[08:48:16] Using gulpfile ~/git/web-build/gulpfile.babel.js
[08:48:16] Starting 'jshint'...
[08:48:16] Starting 'clean:reports'...
[08:48:16] Starting 'clean:work'...
[08:48:16] Finished 'clean:reports' after 13 ms
[08:48:16] Starting 'reports:complexity'...
[08:48:16] Finished 'reports:complexity' after 7.08 ms
[08:48:16] Finished 'clean:work' after 311 ms
[08:48:16] Starting 'assets'...
[08:48:16] Starting 'bundle:dev:js'...
[08:48:16] Starting 'bundle:dev:sass'...
[08:48:16] Finished 'jshint' after 525 ms
[08:48:16] Starting 'test:unit'...
[08:48:18] 'test:unit' errored after 1.43 s
[08:48:18] Error: EMFILE, too many open files '/Users/jay.paulson/git/web-build/spec/unit'
    at Object.fs.readdirSync (fs.js:665:18)
    at GlobSync._readdir (/Users/jay.paulson/git/web-build/node_modules/glob/sync.js:275:41)
    at GlobSync._processGlobStar (/Users/jay.paulson/git/web-build/node_modules/glob/sync.js:330:22)
    at GlobSync._process (/Users/jay.paulson/git/web-build/node_modules/glob/sync.js:128:10)
    at new GlobSync (/Users/jay.paulson/git/web-build/node_modules/glob/sync.js:46:10)
    at new Glob (/Users/jay.paulson/git/web-build/node_modules/glob/glob.js:111:12)
    at Promise.all.cancellable.then.self.buckets (/Users/jay.paulson/git/web-build/node_modules/karma/lib/file-list.js:161:14)
    at Array.map (native)
    at [object Object].List._refresh (/Users/jay.paulson/git/web-build/node_modules/karma/lib/file-list.js:153:37)
    at [object Object].List.refresh (/Users/jay.paulson/git/web-build/node_modules/karma/lib/file-list.js:252:27)
    at [object Object].Server._start (/Users/jay.paulson/git/web-build/node_modules/karma/lib/server.js:177:12)
    at [object Object].invoke (/Users/jay.paulson/git/web-build/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at [object Object].Server.start (/Users/jay.paulson/git/web-build/node_modules/karma/lib/server.js:101:18)
    at Gulp._gulp2.default.task.preProcessors (/Users/jay.paulson/git/web-build/build/tasks/test.js:62:14)
    at module.exports (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
Unhandled rejection Error: Unable to load registry %github%
    at process._tickCallback (node.js:419:13)
From previous event:
    at DestroyableTransform._transform (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/index.js:40:10)
    at DestroyableTransform.Transform._read (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/jay.paulson/git/web-build/node_modules/gulp-jspm/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at DestroyableTransform.ondata (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:574:20)
    at DestroyableTransform.emit (events.js:95:17)
    at readableAddChunk (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:198:16)
    at DestroyableTransform.Readable.push (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DestroyableTransform.Transform.push (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at DestroyableTransform.sourceMapInit [as _transform] (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/index.js:122:10)
    at DestroyableTransform.Transform._read (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/jay.paulson/git/web-build/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/jay.paulson/git/web-build/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
[08:48:22] Finished 'bundle:dev:sass' after 5.79 s
[08:48:22] Finished 'assets' after 5.86 s
```
